config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :treatments, only: [ :index, :new, :create] do
      resources :trackers, only: [ :index, :new, :create]
      resources :categories, only: [ :index, :show ]

    end

      #resources :trackers, only: [ :edit, :update ]
    # tracker_index == dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :trackers, dependent: :destroy

  # validates :title, presence: true, inclusion: { in: ['sleep', 'stress', 'workout', 'diet', 'sun', 'humidity', 'temperature', 'pollution', 'medication', 'products', 'supplements', 'treatments'] }
  # validates :group, presence: true, inclusion: { in: ['skincare', 'environmental', 'lifestyle']}

  CATEGORY = {
  skincare: ['medications', 'products', 'supplements', 'progress'],
  environmental: ['sun', 'humidity', 'temperature', 'pollution'],
  lifestyle: ['sleep', 'stress', 'workout', 'diet']
  }

  validate :pairs_do_match

  def pairs_do_match
    unless CATEGORY[self.group.to_sym].include?(self.title)
      errors.add(:key, "key and value pair don't match")
      errors.add(:value, "key and value pair don't match")
    end
  end
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  belongs_to :treatment
  has_one_attached :photo
  belongs_to :category

  validates :rating, presence: true, numericality: { in: 0..10 }
  validates :notes, presence: true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user
  has_many :trackers

  validates :skin_condition, presence: true, inclusion: { in: ['Eczema', 'Rash', 'Acne', 'Psoriasis'] }
  validates :start_date, presence: true
  validates :status, presence: true, inclusion: { in: ['start', 'in progress', 'end'] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :treatments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # include Pundit

  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :email, :password, :age, :gender, :skin_type, :skin_color])

    #  # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :email, :password, :age, :gender, :skin_type, :skin_color])
  end

  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  # private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @skincare = Category.where(group: 'skincare')
    @environmental = Category.where(group: 'environmental')
    @lifestyle = Category.where(group: 'lifestyle')

    @categories = Category.all
    @treatment = Treatment.find(params[:treatment_id])

    # @tracker = Tracker.new
  end

  def show
    @category = Category.find(params[:id])
    @treatment = Treatment.find(params[:treatment_id])
    @trackers = Tracker.where(category: @category, treatment: @treatment).order('created_at DESC')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [ :show, :edit, :update, :destroy ]
  def index
    # @trackers = Tracker.all
    start_date = params.fetch(:start_date, Date.today).to_date
    @progress_category_id = Category.find_by_title("progress").id
    @treatment = Treatment.find(params[:treatment_id])
    @trackers = @treatment.trackers.where(created_at: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def show
  end

  def new
    @tracker = Tracker.new
    @treatment = Treatment.find(params[:treatment_id])
    @category = Category.find(params[:category_id])
  end

  def create
    @tracker = Tracker.new(tracker_params)
    @treatment = Treatment.find(params[:treatment_id])
    @category = Category.find(params[:tracker][:category_id])
    @tracker.treatment = @treatment
    @tracker.category  = @category
    @tracker.save

    redirect_to treatment_category_path(@treatment, @category)
  end

  def edit
  end

  def update
    @tracker.update(tracker_params)
    redirect_to tracker_path(@tracker)
  end

  def destroy
    @tracker.destroy
    redirect_to tracker_path
  end

  private

  def tracker_params
    params.require(:tracker).permit(:rating, :notes, :photo, :category_id)
  end

  def set_tracker
    @tracker = Tracker.find(params[:id])
    authorize @tracker
  end

end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  def index
    @treatments = Treatment.all
    if params[:query].present?
    else
      puts "No treatments added"
     end
  end

#   def show
#     @treatment = treatment_params
#   end

  def new
    @treatment = Treatment.new
  end

  def create
    @treatment = Treatment.new(treatment_params)
    @treatment.user = current_user
    if @treatment.save
      redirect_to treatments_path
    else
      render :new
    end
  end

  def edit
    @treatment = treatment_params
  end

  def update
    @treatment = treatment_params
    @treatment.update
    redirect_to treatments_path(@treatment)
  end

  def destroy
    @treatment = treatment_params
    @treatment.destroy
    redirect_to treatments_path
  end

  private

  def treatment_params
    params.require(:treatment).permit(:skin_condition, :start_date, :end_date, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/categories/_other.html.erb
<div>
  <h1><%= category.title.capitalize %></h1>
</div>
<div>
  <h5><span><%= "You haven’t uploaded any trackers here yet!" if trackers.empty? %></span></h5>
</div>
  <div class="trackers-both">
    <div class="same-tracker">
      <%= link_to new_treatment_tracker_path({
        treatment_id: treatment.id,
        category_id: category.id,
        group: category.group
      }) do %>
      <i class="fas fa-plus"></i>
      Tracker here
      <% end %>
    </div>
    <div class="new-tracker">
      <%= link_to treatment_categories_path, label: '<i class="far fa-plus-square"></i>'.html_safe do %>
      <i class="fas fa-plus"></i>
      Other tracker
      <% end %>
    </div>
  </div>

<div class="chart">
  <%= line_chart trackers.group(:created_at).maximum(:rating) %>
</div>

    <div class="card-tracker-all">
      <% latest_trackers = @trackers.last(5) %>

      <% latest_trackers.each do |tracker| %>
        <div class="card-tracker" id="border-radius">
          <div class="card-tracker-infos">




            <div class="card-tracker-infos-details" id="title">
              <p><b><%= tracker.category.title %> | <%= tracker.category.group %></b></p>
              <p>rating: <%= tracker.rating %></p>
              <p>"<%= tracker.notes%>"</p>
          </div>
                      <div class="date-icon">
            <div class="card-tracker-icon">
              <p style="font-weight: bold;"><%= tracker.created_at.strftime("%-d %B %Y")%> </p>

                <% if tracker.category.group == "skincare" %>
                  <div class="btn btn-icon btn-skincare" style="height: 50px; width: 50px">
                    <% if tracker.category.title == "medications" %>
                      <i id="c" class="fas fa-prescription-bottle-alt"></i>
                    <% elsif tracker.category.title == "products" %>
                      <i id="c" class="fas fa-prescription-bottle"></i>
                    <% elsif tracker.category.title == "supplements" %>
                      <i id="c" class="fas fa-pills"></i>
                    <% elsif tracker.category.title == "progress" %>
                      <i id="c" class="fas fa-thumbs-up"></i>
                    <% end %>
                  </div>

                <% elsif tracker.category.group == "environmental" %>
                  <div class="btn btn-icon btn-environmental" style="height: 50px; width: 50px;">
                    <% if tracker.category.title == "sun" %>
                      <i id="c" class="far fa-sun"></i>
                    <% elsif tracker.category.title == "humidity" %>
                      <i id="c" class="fas fa-water"></i>
                    <% elsif tracker.category.title == "temperature" %>
                      <i id="c" class="fas fa-temperature-high"></i>
                    <% elsif tracker.category.title == "pollution" %>
                      <i id="c" class="fas fa-smog"></i>
                    <% end %>
                  </div>

                <% elsif tracker.category.group == "lifestyle" %>
                  <div class="btn btn-icon btn-lifestyle" style="height: 50px; width: 50px;">
                    <% if tracker.category.title == "sleep" %>
                      <i id="c" class="fas fa-bed"></i>
                    <% elsif tracker.category.title == "stress" %>
                      <i id="c" class="fas fa-sad-cry"></i>
                    <% elsif tracker.category.title == "workout" %>
                      <i id="c" class="fas fa-running"></i>
                    <% elsif tracker.category.title == "diet" %>
                      <i id="c" class="fas fa-hamburger"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
        </div>
      </div>

      <% end %>
    </div>

app/views/categories/_progress.html.erb
<div>
  <h1><%= category.title.capitalize %></h1>
</div>
<div>
  <h5><span><%= "You haven’t uploaded any progress trackers with pictures yet!" if trackers.empty? %></span></h5>

</div>

<br>

<!-- Slider main container -->
<!-- Swiper -->
    <div class="swiper-container" style="margin: 30px;">
      <div class="swiper-wrapper">
        <% trackers.each do |tracker| %>
          <div class="swiper-slide swiper-card">
            <% if tracker.photo.attached? %>
            <%= cl_image_tag tracker.photo.key, height: "100%", class: "carousel-image", id: "border-radius"%>
            <% else %>
              <%= image_tag "Placeholder.jpg", height: "100%", class: "carousel-image", id: "border-radius"%>
            <% end %>

            <div><br></div>
      <div class="swiper-pagination"></div>

            <div class="card-tracker-infos-details" id="progress">
              <p><b><%= tracker.created_at.strftime("%-d %B %Y") %></b></p>
              <p>rating: <%= tracker.rating %></p>
              <p><%= tracker.notes%> </p>
            </div>
          </div>
        <% end %>

      </div>
      <div class="progress-button">
        <h5><%= link_to "New progress tracker", new_treatment_tracker_path({
          treatment_id: treatment.id,
          category_id: category.id,
          group: category.group
          }) %></h5>
      </div>
    </div>

app/views/categories/index.html.erb
<div class="card d-flex align-content-center" id="border-radius" style="width: 22rem; margin-top: 54px;">
  <div class="card-body">

        <h5 class="card-title">Skin care</h5>
          <div class="card-group d-flex">
            <% @skincare.each do |skincare| %>
              <div class="btn-category">
                <%= link_to new_treatment_tracker_path(group: skincare.group, category_id: skincare.id, title: "Skin condition today:"), class: "btn btn-icon btn-skincare" do %>
                  <% if skincare.title == "progress" %>
                    <i id="i" class="far fa-thumbs-up"></i>
                  <% elsif skincare.title == "medications" %>
                    <i id="i" class="fas fa-prescription-bottle-alt"></i>
                  <% elsif skincare.title == "products" %>
                    <i id="i" class="fas fa-prescription-bottle"></i>
                  <% elsif skincare.title == "supplements" %>
                    <i id="i" class="fas fa-pills"></i>
                  <% end %>
                <% end %>
                <p><%= skincare.title.capitalize %></p>
              </div>
            <% end %>
          </div>

        <h5 class="card-title">Environmental</h5>
          <div class="card-group d-flex">
            <% @environmental.each do |environmental| %>
              <div class="btn-category">
                <%= link_to new_treatment_tracker_path(group: environmental.group, category_id: environmental.id, title: "Sun exposure today:"), class: "btn btn-icon btn-environmental" do %>
                  <% if environmental.title == "sun" %>
                    <i id="i" class="far fa-sun"></i>
                  <% elsif environmental.title == "humidity" %>
                    <i id="i" class="fas fa-water"></i>
                  <% elsif environmental.title == "temperature" %>
                    <i id="i" class="fas fa-temperature-high"></i>
                  <% elsif environmental.title == "pollution" %>
                    <i id="i" class="fas fa-smog"></i>
                  <% end %>
                <% end %>
              <p><%= environmental.title.capitalize %></p>
            </div>
          <% end %>
        </div>

          <h5 class="card-title">Lifestyle</h5>
            <div class="card-group d-flex">
              <% @lifestyle.each do |lifestyle| %>
                <div class="btn-category">
                  <%= link_to new_treatment_tracker_path(group: lifestyle.group, category_id: lifestyle.id, title: "Sleep quality today:"), class: "btn btn-icon btn-lifestyle" do %>
                    <% if lifestyle.title == "sleep" %>
                      <i id="i" class="fas fa-bed"></i>
                    <% elsif lifestyle.title == "stress" %>
                      <i id="i" class="fas fa-sad-cry"></i>
                    <% elsif lifestyle.title == "workout" %>
                      <i id="i" class="fas fa-running"></i>
                    <% elsif lifestyle.title == "diet" %>
                      <i id="i" class="fas fa-hamburger"></i>
                    <% end %>
                  <% end %>
                <p><%= lifestyle.title.capitalize %></p>
              </div>
            <% end %>
          </div>

  </div>
</div>

app/views/categories/show.html.erb
<% if @category.title == "progress" %>
  <%= render "progress", treatment: @treatment, category: @category, trackers: @trackers %>
<% else %>
  <%= render "other", treatment: @treatment, category: @category, trackers: @trackers %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title> <%= "Holyskin | Be well in your skin" %></title>
    <meta name="description" content="<%= "Easily identify your skin triggers by tracking your skincare products, lifestyle choices, habits & more" %>">
    <%= favicon_link_tag %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="og_image2.jpeg"/>
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

        <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!--   <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="custom.css"> -->

    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">

    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= render 'shared/ios_pwa_links' %>

  </head>

  <body>
    <div id="page-container">
      <div id="content-wrap">
        <%= render 'shared/navbar' unless params[:controller] == 'pages' && params[:action] == 'home' %>
          <div id="<%= 'yield-wrap' unless params[:controller] == 'trackers' && params[:action] == 'index'%>">
            <%= yield %>
          </div>
        <%= render 'shared/footer' unless params[:controller] == 'pages' && params[:action] == 'home' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<body id="landing">
<a href="/treatments" class="stretched-link">
  <div class="image_tag">
    <%= image_tag ('happy.png'), style: "margin: 20px;" %>
    <h1 class="ml7">
    <span class="text-wrapper">
      <span class="letters">Holy Skin</span>
    </span>
    </h1>
    <h2>Be well in your skin</h2>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

 <!--  <h1 class="text-light">Pure CSS Animated Gradient Background</h1>

<div class="btn-group mt-2 mb-4" role="group" aria-label="actionButtons">
  <a href="https://codepen-api-export-production.s3.us-west-2.amazonaws.com/zip/PEN/pyBNzX/1578778289271/pure-css-gradient-background-animation.zip" class="d-block btn btn-outline-light" download><i class="fas fa-file-download mr-2"></i>Download Source</a>
  <a href="https://manuelpinto.in" target="_blank" class="d-block btn btn-outline-light">Visit my Website<i class="fas fa-external-link-square-alt ml-2"></i></a>
</div>

<h6 class="text-light small font-weight-bold"><i class="fas fa-code"></i> with <i class="fas fa-heart"></i> by Manuel Pinto</h6> -->

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>
 -->  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>
</a>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-elements">
    <div class="footer-links">

      <a href="/treatments"><i class="fas fa-home"></i></a>

<!--       <i class="fas fa-calendar-alt"><%# link_to treatment_trackers_path(@treatment_id) %></i>
 -->
      <% if @treatment && !@treatment.id.nil? %>
      <%# raise %>
        <%= link_to treatment_trackers_path(@treatment) do %>
          <i class="far fa-calendar-alt"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/trackers/index.html.erb
<div class="dashboard-layout container" id="dashboard">

<div class="dashboard-test">
  <h3><%= @treatment.skin_condition.capitalize %></h3>
  <h2>Hey, <%= current_user.full_name.capitalize %>!</h2>
</div>

<!-- <div class="popup" onclick="myFunction()">Click me to toggle the popup!
  <span class="popuptext" id="myPopup">A Simple Popup!</span>
</div> -->

<div class="dashboard-layout">
  <%= month_calendar(events: @trackers, attribute: :created_at) do |date, trackers| %>
    <%= date.strftime("%e") %>

    <div class="tracker-display">
      <% trackers.each do |tracker| %>
        <div class="tracker">
          <% if tracker.category.group == "skincare" %>
            <p class="bg-color-blue"> </p>
          <% elsif tracker.category.group == "environmental" %>
            <p class="bg-color-green"> </p>
          <% elsif tracker.category.group == "lifestyle"  %>
            <p class="bg-color-red"> </p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

    <div class="card-tracker-all">
      <% latest_trackers = @trackers.last(5) %>

      <% latest_trackers.each do |tracker| %>
        <div class="card-tracker" id="border-radius">
          <div class="card-tracker-infos">

          <div class="date-icon">
            <div class="card-tracker-icon">
              <p style="font-weight: bold;"><%= tracker.created_at.strftime("%-d %B %Y")%> </p>

                <% if tracker.category.group == "skincare" %>
                  <div class="btn btn-icon btn-skincare" style="height: 50px; width: 50px">
                    <% if tracker.category.title == "medications" %>
                      <i id="c" class="fas fa-prescription-bottle-alt"></i>
                    <% elsif tracker.category.title == "products" %>
                      <i id="c" class="fas fa-prescription-bottle"></i>
                    <% elsif tracker.category.title == "supplements" %>
                      <i id="c" class="fas fa-pills"></i>
                    <% elsif tracker.category.title == "progress" %>
                      <i id="c" class="fas fa-thumbs-up"></i>
                    <% end %>
                  </div>

                <% elsif tracker.category.group == "environmental" %>
                  <div class="btn btn-icon btn-environmental" style="height: 50px; width: 50px;">
                    <% if tracker.category.title == "sun" %>
                      <i id="c" class="far fa-sun"></i>
                    <% elsif tracker.category.title == "humidity" %>
                      <i id="c" class="fas fa-water"></i>
                    <% elsif tracker.category.title == "temperature" %>
                      <i id="c" class="fas fa-temperature-high"></i>
                    <% elsif tracker.category.title == "pollution" %>
                      <i id="c" class="fas fa-smog"></i>
                    <% end %>
                  </div>

                <% elsif tracker.category.group == "lifestyle" %>
                  <div class="btn btn-icon btn-lifestyle" style="height: 50px; width: 50px;">
                    <% if tracker.category.title == "sleep" %>
                      <i id="c" class="fas fa-bed"></i>
                    <% elsif tracker.category.title == "stress" %>
                      <i id="c" class="fas fa-sad-cry"></i>
                    <% elsif tracker.category.title == "workout" %>
                      <i id="c" class="fas fa-running"></i>
                    <% elsif tracker.category.title == "diet" %>
                      <i id="c" class="fas fa-hamburger"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>

            <div class="card-tracker-infos-details">
              <p style="font-size: 8px;" ><b><%= tracker.category.title %> | <%= tracker.category.group %></b></p>
              <p>rating: <%= tracker.rating %></p>
              <p>"<%= tracker.notes%>"</p>
          </div>

        </div>
      </div>

      <% end %>
    </div>

  <div class="cards-links">
    <div class="card-tracker-links" id="border-radius">
      <div id="link">
        <%= image_tag ('Long.png'), style: "height: 90px;width: auto;" %>
          <h5 id="new"><%= link_to "Progress Gallery", treatment_category_path(@treatment.id, @progress_category_id) %> </h5>
      </div>
    </div>

    <div class="card-tracker-links" id="border-radius">
      <div id="link">
        <%= image_tag ('plus.png'), style: "height: 100px;width: auto;"%>
          <h5 id="new"><%= link_to "New Entry", treatment_categories_path %></h5>
      </div>
    </div>
 <!--    <div class="card-tracker-links" >
      <i class="fas fa-plus-circle" id="link" style="color: #FFC65A;">
        <h5 id="new"><%= link_to "New Entry", treatment_categories_path %></h5>
      </i>
    </div> -->

    <!-- <div class="progress-gallery-link"> -->
  </div>

  </div>
</div>

app/views/trackers/new.html.erb
<%= render "shared/form" %>

app/views/treatments/index.html.erb
<div class="index-layout">
  <h1 class="treatment-header"> Treatments </h1>
  <div class="all-cards-treatment">
    <div class="card-treatment">
      <% @treatments.each do |treatment| %>
        <h3> <%= link_to treatment_trackers_path(treatment), class: "card-link" do %>
         <!-- <div> -->
          <div class="card-treatment-info">
          <h3><%= treatment.skin_condition %></h3>
          </div>
       <!--  </div> -->
      <% end %>
    <% end %>
    </h3>
   </div>
  </div>

  <br>
  <br>
  <br>


  <div class="card-add-treatment" id="new-button">
     <%= link_to "New Treatment", new_treatment_path, id:"new-button" %>
  </div>
</div>